select 
    `Primary Contact Name` as full_contact_name,
    string(null) as last_name,
    string(null) as first_name,
    `Primary Contact Role` as title,
    `Name` as company,
    `Address` as address1,
    string(null) as address2,
    string(null) as city,
    `State` as state,
    right(`Address`, 5) as zip,
    `County` as county,
    'US' as country,
    concat("1", replace(`Phone`, '-', '')) as phone1,
    concat("1", replace(`Phone`, '-', '')) as mobile_phone,
    string(null) as email,
    string(null) as website,
    cast(null as numeric) as capacity,
    null as salesforce_lead_id,
    null as is_deleted,
    'source1' as lead_source,
    null as status,
    null as is_converted,
    current_date as created_date,
    null as last_modified_date,
    null as last_activity_date,
    null as last_viewed_date,
    null as last_referenced_date,
    null as email_bounced_date,
    null as email_bounced_reason,
    null as outreach_stage,
    null as lead_source_last_updated, 
    string(null) as provider_id,
    string(null) as accepts_financial_aid,
    string(null) as ages_served,
    `Expiration Date` as certificate_expiration_date,
    string(null) as curriculum_type,
    string(null) as language,
    `Status` as license_status,
    `First Issue Date` as license_issued,
    cast(replace(`Credential Number`, '-', '') as numeric) as license_number,
    date(null) as license_renewed,
    `Credential Type` as license_type,
    `Name` as licensee_name,
    cast(null as numeric) as max_age,
    cast(null as numeric) as min_age,
    string(null) as operator,
    string(null) as schedule,
    string(null) as facility_type

from brightwheel.source1