
SELECT 
    concat(first_name, " ", last_name) as full_contact_name,
    last_name,
    first_name,
    title,
    company,
    street as address1,
    string(null) as address2,
    city,
    state,
    postal_code as zip,
    string(null) as county,
    country,
    cast(phone as string) as phone1,
    cast(mobile_phone as string) as mobile_phone,
    email,
    website,
    cast(capacity_c as numeric) as capacity,
    id as salesforce_lead_id,
    is_deleted,
    lead_source,
    status,
    is_converted,
    cast(created_date as date) as created_date,
    last_modified_date,
    last_activity_date,
    last_viewed_date,
    last_referenced_date,
    email_bounced_date,
    email_bounced_reason,
    outreach_stage_c as outreach_stage,
    lead_source_last_updated_c as lead_source_last_updated, 
    cast(brightwheel_school_uuid_c as string) as provider_id,

    string(null) as accepts_financial_aid,
    string(null) as ages_served,
    date(null) as certificate_expiration_date,
    string(null) as curriculum_type,
    string(null) as language,
    string(null) as license_status,
    date(null) as license_issued,
    cast(null as numeric) as license_number,
    date(null) as license_renewed,
    string(null) as license_type,
    string(null) as licensee_name,
    cast(null as numeric) as max_age,
    cast(null as numeric) as min_age,
    string(null) as operator,
    string(null) as schedule,
    string(null) as facility_type

FROM brightwheel-takehome.brightwheel.salesforce_leads