select 
    `Primary Contact Name` as full_contact_name,
    null as last_name,
    null as first_name,
    `Primary Contact Role` as title,
    `Name` as company,
    `Address` as address1,
    null as address2,
    null as city,
    `State` as state,
    right(`Address`, 5) as zip,
    `County` as county,
    'US' as country,
    concat("1", replace(`Phone`, '-', '')) as phone1,
    concat("1", replace(`Phone`, '-', '')) as mobile_phone,
    null as email,
    null as website,
    null as current_enrollment,
    null as capacity,
    null as salesforce_lead_id,
    null as is_deleted,
    'source1' as lead_source,
    null as status,
    null as is_converted,
    current_date as created_date,
    null as last_modified_date,
    null as last_activity_date,
    null as last_viewed_date,
    null as last_referenced_date,
    null as email_bounced_date,
    null as email_bounced_reason,
    null as outreach_stage,
    null as lead_source_last_updated,
    null as provider_id,
    null as accepts_financial_aid,
    null as ages_served,
    `Expiration Date` as certificate_expiration_date,
    null as curriculum_type,
    null as language,
    `Status` as license_status,
    `First Issue Date` as license_issued,
    `Credential Number` as license_number,
    null as license_renewed,
    `Credential Type` as license_type,
    `Name` as licensee_name,
    null as max_age,
    null as min_age,
    null as operator,
    null as schedule,
    null as facility_type

from brightwheel.source1